In [1]:
# CyberShield Analytics
## Machine Learning Preparation

"Preparación de variables y features para clasificación de ataques cibernéticos."

'Preparación de variables y features para clasificación de ataques cibernéticos.'

In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_parquet(
    '../data/clean/cybersecurity_attacks_clean.parquet'
)

In [4]:
df.head()

,timestamp,source_ip_address,destination_ip_address,source_port,destination_port,protocol,packet_length,packet_type,traffic_type,payload_data,...,device_information,network_segment,geo_location_data,proxy_information,firewall_logs,ids_ips_alerts,log_source,mexico_state,latitude,longitude
0,2023-05-30 06:33:58,103.216.15.12,84.9.164.252,31225,17616,ICMP,503,Data,HTTP,Qui natus odio asperiores nam. Optio nobis ius...,...,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment A,"Jamshedpur, Sikkim",150.9.97.135,Log Data,NaN,Server,Ciudad de México,19.4326,-99.1332
1,2020-08-26 07:08:30,78.199.217.198,66.191.137.154,17245,48166,ICMP,1174,Data,HTTP,Aperiam quos modi officiis veritatis rem. Omni...,...,Mozilla/5.0 (compatible; MSIE 8.0; Windows NT ...,Segment B,"Bilaspur, Nagaland",NaN,Log Data,NaN,Firewall,Jalisco,20.6597,-103.3496
2,2022-11-13 08:23:25,63.79.210.48,198.219.82.17,16811,53600,UDP,306,Control,HTTP,Perferendis sapiente vitae soluta. Hic delectu...,...,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,Segment C,"Bokaro, Rajasthan",114.133.48.179,Log Data,Alert Data,Firewall,Nuevo León,25.6866,-100.3161
3,2023-07-02 10:38:46,163.42.196.10,101.228.192.255,20018,32534,UDP,385,Data,HTTP,Totam maxime beatae expedita explicabo porro l...,...,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_11_5; ...,Segment B,"Jaunpur, Rajasthan",NaN,NaN,Alert Data,Firewall,Nuevo León,25.6866,-100.3161
4,2023-07-16 13:11:07,71.166.185.76,189.243.174.238,6131,26646,TCP,1462,Data,DNS,Odit nesciunt dolorem nisi iste iusto. Animi v...,...,Mozilla/5.0 (compatible; MSIE 5.0; Windows NT ...,Segment C,"Anantapur, Tripura",149.6.110.119,NaN,Alert Data,Firewall,Puebla,19.0414,-98.2063

In [5]:
features = [
    'protocol',
    'packet_length',
    'traffic_type',
    'anomaly_scores',
    'severity_level',
    'network_segment',
    'mexico_state'
]

target = 'attack_type'

In [6]:
ml_df = df[features + [target]].copy()

In [7]:
ml_df.head()

,protocol,packet_length,traffic_type,anomaly_scores,severity_level,network_segment,mexico_state,attack_type
0,ICMP,503,HTTP,28.67,Low,Segment A,Ciudad de México,Malware
1,ICMP,1174,HTTP,51.50,Low,Segment B,Jalisco,Malware
2,UDP,306,HTTP,87.42,Low,Segment C,Nuevo León,DDoS
3,UDP,385,HTTP,15.79,Medium,Segment B,Nuevo León,Malware
4,TCP,1462,DNS,0.52,Low,Segment C,Puebla,DDoS

In [9]:
categorical_columns = ml_df.select_dtypes(
    include=['object', 'string']
).columns
categorical_columns

Index(['protocol', 'traffic_type', 'severity_level', 'network_segment',
       'mexico_state', 'attack_type'],
      dtype='str')

In [10]:
encoders = {}

for column in categorical_columns:
    
    encoder = LabelEncoder()
    
    ml_df[column] = encoder.fit_transform(
        ml_df[column]
    )
    
    encoders[column] = encoder

In [11]:
ml_df.head()

,protocol,packet_length,traffic_type,anomaly_scores,severity_level,network_segment,mexico_state,attack_type
0,0,503,2,28.67,1,0,3,2
1,0,1174,2,51.50,1,1,7,2
2,2,306,2,87.42,1,2,9,0
3,2,385,2,15.79,2,1,9,2
4,1,1462,0,0.52,1,2,11,0

In [12]:
ml_df.isnull().sum()

protocol           0
packet_length      0
traffic_type       0
anomaly_scores     0
severity_level     0
network_segment    0
mexico_state       0
attack_type        0
dtype: int64

In [13]:
ml_df.shape

(40000, 8)

In [14]:
ml_df.to_parquet(
    '../data/processed/cybersecurity_ml_ready.parquet',
    index=False
)

In [15]:
validation_df = pd.read_parquet(
    '../data/processed/cybersecurity_ml_ready.parquet'
)

validation_df.head()

,protocol,packet_length,traffic_type,anomaly_scores,severity_level,network_segment,mexico_state,attack_type
0,0,503,2,28.67,1,0,3,2
1,0,1174,2,51.50,1,1,7,2
2,2,306,2,87.42,1,2,9,0
3,2,385,2,15.79,2,1,9,2
4,1,1462,0,0.52,1,2,11,0